### ISSUE TITLE
Slack: The code cleaner is broken

### ISSUE THREAD

**Issue by hemangandhi** [HackRU/frontend#18]
The message cleanser, that removes emotes (`:something:`) and mentions (`<garbage>`) is broken. It just removes anything between colons and brackets, without insisting that they match.

This should be fixed... the interview submissions may help.

**Comment by TresTres** [comment]
Slack component is now completely functional - apparently the format of the response changed somewhat, so that was yet another factor that broke the original code.  

The current component, does work, but unfortunately the following case breaks it:

![image](https://user-images.githubusercontent.com/14167519/43507120-371fa3f6-953a-11e8-8638-c677a088f07d.png)

Resulting in: 

![image](https://user-images.githubusercontent.com/14167519/43507153-4fce3eee-953a-11e8-9e68-78193736386b.png)

So much for super simple regex 😢 
We'll also have to figure a way to do better text-wrapping for URLs:

![image](https://user-images.githubusercontent.com/14167519/43507208-707f2b9e-953a-11e8-971e-b10b1194c336.png)

**Comment by ryanisaacg** [comment]
I fixed half of the bug but have no idea what to do for word wrapping. I think that might be a CSS issue?

**Comment by TresTres** [comment]
Probably.  Let's close this for now and reference a new issue when we better define the remaining bug.
